### ISSUE TITLE
Dates as Data Lesson: Dates stored as integers section 404 link

### ISSUE THREAD

**Issue by U2NG** [datacarpentry/spreadsheets-socialsci#133]
The link in the yellow box section for "dates must be checked for accuracy when exporting data from Excel" link redirects to a 404: page not found.

**Comment by burrowsdt** [comment]
This is a great catch - thanks for opening the issue. The correct link is [https://uc3.cdlib.org/2014/04/09/abandon-all-hope-ye-who-enter-dates-in-excel/](https://uc3.cdlib.org/2014/04/09/abandon-all-hope-ye-who-enter-dates-in-excel/) and the lesson will be updated shortly.
