### ISSUE TITLE
Lesson Contribution - SAFI subset

### ISSUE THREAD

**Issue by Talishask** [datacarpentry/spreadsheets-socialsci#135]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

----

In the "Data Organization in Spreadsheets for Social Scientists - Dates as Data", the assignment "Separating dates into components" starts with the file SAFI_dates.xlsx, a subset of the data from the SAFI interviews, but it may be confusing if someone does not follow the SAFI_messy =>SAFI_clean steps.

**Comment by josenino95** [comment]
I don't think a change is needed here, as the exercise callout box clearly states that people should download the SAFI_dates.xlsx file. And also there should be no confusion with SAFI_messy as that file doesn't contain dates.
