### ISSUE TITLE
02-common-mistakes link to  "Nine simple ways to make it easier to (re)use your data" broken

### ISSUE THREAD

**Issue by marioa** [datacarpentry/spreadsheets-socialsci#137]
The current link gives a "Page not found". The following link works:

* https://ojs.library.queensu.ca/index.php/IEE/article/view/4608

**Comment by burrowsdt** [comment]
Thanks @marioa  - if anyone wants to tackle this with a pull request, feel free! Otherwise I will make the change shortly.
