### ISSUE TITLE
Broken link to lesson discussion 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/spreadsheets-socialsci#161]
On this page (https://datacarpentry.org/spreadsheets-socialsci/05-exporting-data.html) there is a link to the lesson discussion page that is not working.  

> For more of a discussion on data formats and potential issues with commas within datasets see [the Ecology Spreadsheets lesson discussion page](https://www.datacarpentry.org/spreadsheet-ecology-lesson/discuss/).

**Comment by zkamvar** [comment]
The trailing slash of that URL needs to be removed for it to work

**Comment by Bsolodzi** [comment]
@maneesha the link is fixed now, please do let me know if it works.
