### ISSUE TITLE
Typos and wording

### ISSUE THREAD

**Issue by NoaYaari** [datacarpentry/spreadsheets-socialsci#170]
1 - “e.g.” should come with a comma after the second period. In the lesson, only 3/13 have a comma.
2 - Episode “Structuring data in spreadsheets” -> metadata -> typo -> “an” in “Codebooks will often describe the way a variable has been constructed, what prompt was associated with it in an survey or interview, and what the meaning of various values are.”
3 - Same section -> typo -> unneeded first “are” in “Additionally, file or database level metadata describes how files that make up the dataset relate to each other; what format are they are in; and whether they supersede or are superseded by previous files.”
4 - Same section -> broken link in “MANTRA”
5 - Episode “Common Spreadsheet Errors” -> typo -> unneeded comma after “spreadsheets” in “Making small changes to the way you format your data in spreadsheets, can have a great impact on efficiency and reliability when it comes to data cleaning and analysis.”
6 - Episode “Using multiple tables” -> wording -> soften “so don’t do this!” 
7 - Same section -> wording -> unneeded “(for example)” in “In the example above, the computer will see (for example) row 24 and assume that all columns A-J refer to the same sample.” 
8 - Episode “Using multiple tabs” -> wording -> unneeded “for instance” in “Say, for instance, you make a separate tab for each day you take a measurement.”
9 - Episode “Using problematic null values” -> typo and wording -> period after “al” -> name of journal unneeded in “White et al, 2013, explain good choices for indicating null values for different software applications in their article: Nine simple ways to make it easier to (re)use your data. Ideas in Ecology and Evolution.” 
10 - Episode “Using formatting to convey information” -> wording -> needed “and” before “leaving” in “Example: highlighting cells, rows or columns that should be excluded from an analysis, leaving blank rows to indicate separations in data.”
11 - Episode “Using special characters in data” -> layout -> title of episode aligns to the right.
12 - Episode “Dates as Data” -> wording -> inconsistency in the order of “Month, Day, Year.”
13 - Episode “Date formats in spreadsheets” -> wording -> better “or” than “and” after “observations” in “Ambiguity can creep into your data when working with dates when there are regional variations either in your observations and when you or your team might be working with different versions or suites of software products (e.g., LibreOffice, Microsoft Excel, Gnumeric).”
14 - Episode “Exporting Data” -> wording -> better “our discussion” than “how we talked about” or simply provide the example in “As an example of inconsistencies in data storage, do you remember how we talked about how Excel stores dates earlier?”

**Comment by bencomp** [comment]
Nice work, @NoaYaari! These are very actionable points, but I will leave further commenting to the lesson's maintainers.

For reference, your point 11 is the same as #160 – but viewed from the other side :)

**Comment by NoaYaari** [comment]
Thanks, @bencomp - #160... yes, from the table's side! 

Very best : )

**Comment by josenino95** [comment]
Thank you @NoaYaari for your detailed review of the lesson. I've worked on all the issues you pointed out here, as I agree with them. The fix is now live.
