### ISSUE TITLE
very short paragraphs look odd

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheets-socialsci#18]
The [first episode](http://www.datacarpentry.org/spreadsheets-socialsci/01-creating-tables/) has a section with a lot of one sentence paragraphs. These look very strange to me. It would be better to collapse this to one or two paragraphs.

**Comment by ErinBecker** [comment]
The first section in the [fifth episode](http://www.datacarpentry.org/spreadsheets-socialsci/05-quality-control/) also has this issue.

**Comment by chris-prener** [comment]
Agreed @ErinBecker

**Comment by ErinBecker** [comment]
Closed with #25.
