### ISSUE TITLE
caveat for date handling

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheets-socialsci#22]
[Episode 4](http://www.datacarpentry.org/spreadsheets-socialsci/04-dates/) has the text:

>>This regional variation is handled automatically by the spreadsheet program so that when you are typing in dates they appear as you would expect. If you try to type in a US format date into a UK version of Excel, it may or may not be treated as a date.

The phrase "they appear as you would expect" is somewhat misleading. They may or may not appear as you would expect! If, for example, you are a researcher from the US working in the UK and using your new lab's computer and software, you may type in a US date and have it render according to UK rules. Alternatively, if that same person is using their personal computer and sharing files back and forth with a collaborator who uses a UK version of Excel, there will also be problems!

I think it is key here to stress that because Excel is manipulating the values that you enter (and storing them in some non-transparent way) you can't be sure exactly what you're getting (ie it's not reproducible). That's why it's always best to store dates not as dates but as numbers using multiple columns to separate the components (e.g. month, day, year).

**Comment by chris-prener** [comment]
see also #23

**Comment by ErinBecker** [comment]
Fixed with https://github.com/datacarpentry/spreadsheets-socialsci/pull/38
