### ISSUE TITLE
remove coloration and special formatting from report_data_c.xlsx

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheets-socialsci#30]
Episode 02-reformatting includes an Excel spreadsheet which is intended to be an example of good formatting. However, it includes special formatting like colored celled and text coloration that should be removed.

**Comment by PeterSmyth12** [comment]
The 'special' formatting is introduced automatically by Excel when the data is made into a table in step 5 of the process. There is no information content in the coloring, it aids readability. When you export the data, nothing is lost. 
Surely the point about not using colour is that it masks information that can be lost?

**Comment by ErinBecker** [comment]
Closed in favor of solution proposed in #37.
