### ISSUE TITLE
clarify report_data_o.xlsx

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheets-socialsci#31]
Episode 02-reformatting includes an Excel spreadsheet titled "report_data_o.xlsx". This spreadsheet has a number of individual tables, with each having another header bar off to the right side of that table. It wasn't clear to me at first, but that second header bar is meant to apply to the table to it's left (as extra metadata) and not to be a header for another independent table. Those headers can be moved to immediately below the header line for each table to clarify that they belong with that data. 

Note that this is an example of "bad formatted" data so it's ok to have two header lines per table.

**Comment by PeterSmyth12** [comment]
@ErinBecker you seem to be asking to change one badly formatted layout for another.  If it was changed, then half the formulae in the walk through exercise would have to be changed as well.

**Comment by ErinBecker** [comment]
@PeterSmyth12 - it's true that the formulae would need to be changed, and that's an important point to consider. However, the way this report is currently formatted, I couldn't tell after looking at it several times what the intention of the reporter was in including the second header row off to the right side, rather than combined with the table data. I interpreted it as another table of data that was just missing. If other people interpret the spreadsheet similarly, it would introduce a lot of cognitive burden in making sense of this example. So I think it's worth changing, but I would be ready to change my mind if you know from experience that people didn't find this confusing!

**Comment by ErinBecker** [comment]
I'm working on this issue now.

**Comment by ErinBecker** [comment]
Closed in favor of solution proposed in https://github.com/datacarpentry/spreadsheets-socialsci/issues/37.
