### ISSUE TITLE
reorganization of this lesson

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheets-socialsci#37]
I'm working through the lesson and noticed that there are multiple "toy" datasets that are used for different parts of the lesson. Generally, in Data Carpentry lessons, we try to build all examples around a single dataset (as much as possible) and to have that dataset be somewhat realistic in terms of what the learners would be working with in their everyday workflow. 

This lesson currently uses:
- A toy dataset about "readings" in two different regions ("North" and "South") over nine days in January and February 2015. This is fictional data that doesn't represent anything in particular and is just being used as an example of bad formatting. (see conversation in https://github.com/datacarpentry/spreadsheets-socialsci/issues/32). This data is included as the data files report_data_o.xlsx and report_data_c.xlsx.

- A metadata example from a UK audit of political engagement (http://www.datacarpentry.org/spreadsheets-socialsci/03-formatting-problems/). This is included as this file: audit_of_political_engagement_11_ukda_data_dictionary.rtf. 

- A SAFI dataset about house types and livestock types in Mozambique and Tanzania. This dataset is included as the data file SAFI_results_2. No information about the source of this data appears to be included in the lesson. 

- A small toy dataset consisting of the words "Hello world, how are you" in various permutations. (http://www.datacarpentry.org/spreadsheets-socialsci/06-exporting-data/). 

Thus use of multiple different datasets is confusing and potentially distracting to the learners. I propose that this lesson is reorganized such that all of the exercises use the SAFI dataset. This reorganization involves the following:

- [x] Addition of a description of the SAFI data and a link to the source data
- [x] Deletion of other data files
- [x] Removal of image of "Hello world" dataset from [Episode 1](http://www.datacarpentry.org/spreadsheets-socialsci/01-creating-tables/)
- [x] Moving [Episode 3](http://www.datacarpentry.org/spreadsheets-socialsci/03-formatting-problems/) to immediately after Episode 1. 
- [x] Replacing the metadata section with an example of metadata from the SAFI data. 
- [x] Adjustment of the [Quality control episode](http://www.datacarpentry.org/spreadsheets-socialsci/05-quality-control/) so that the examples refer to the SAFI dataset.
- [x] Adjustment of the [Dates episode](http://www.datacarpentry.org/spreadsheets-socialsci/04-dates/) so that the examples refer to the SAFI dataset (if possible - this data may not include dates).

**Comment by ErinBecker** [comment]
Some information about SAFI: http://www.safi-research.org/

**Comment by PeterSmyth12** [comment]
Hi Erin,

I didn’t know they had a website, but even so you won’t find the data as it hasn’t been published yet.

Regards,

Peter

______________________________________________________________________________________
Peter Smyth
Research Associate
______________________________________________________________________________________
T +44 (0) 161 275 0273
E peter.smyth@manchester.ac.uk<mailto:peter.smyth@manchester.ac.uk>
______________________________________________________________________________________
The Cathie Marsh Institute (CMI)
The University of Manchester
______________________________________________________________________________________
Legal Disclaimer:  Any views expressed by the sender of this message are not necessarily those of the UK Data
Service. This email and any files transmitted with it are confidential and intended solely for the use of
the individual(s) or entity to whom they are addressed.

**Comment by ErinBecker** [comment]
The data has now been published on Figshare and a link to the data publication has been added to the workshop homepage (https://github.com/datacarpentry/socialsci-workshop/pull/11)
