### ISSUE TITLE
reword advice about dealing with data fields that contains commas 

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/spreadsheets-socialsci#41]
The [CSV file specification](https://tools.ietf.org/html/rfc4180#page-2) makes it clear that fields with coma should be enclosed with double-quotes, and are therefore supported. A better recommendation might be to not change the default used by the spreadsheet program in how the text fields are handled.

**Comment by ErinBecker** [comment]
@fmichonneau could you point out the specific section in that episode that is problematic?

**Comment by fmichonneau** [comment]
sorry I thought I did: https://github.com/datacarpentry/spreadsheets-socialsci/blob/gh-pages/_episodes/05-exporting-data.md#caveats-on-commas
