### ISSUE TITLE
A description of the dataset is needed

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/spreadsheets-socialsci#44]
- The goal of the study needs be articulated
- All the variables included in the dataset need to be described, and why they are included in the dataset needs to be explained
- The type of questions that can be asked from the data needs to be articulated
- The full citation information for the dataset needs to be included (as well as possible links to published studies using the dataset).

**Comment by ErinBecker** [comment]
See http://www.datacarpentry.org/socialsci-workshop/data/.

**Comment by ErinBecker** [comment]
Since a link to this data description will be added in addressing https://github.com/datacarpentry/spreadsheets-socialsci/issues/49, I am closing this issue as a duplicate.
