### ISSUE TITLE
Section about metadata should mention metadata standards

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/spreadsheets-socialsci#48]
metadata is more useful if it follows a standard. A quick search indicates that DDI (http://www.ddialliance.org/training/why-use-ddi) is used in the social sciences. Also indicate that librarians might be able to provide help and guidance with this.

**Comment by ErinBecker** [comment]
This would be a fantastic addition to the lessons. I will mark as "refer-to-cac" with the hopes that the Curriculum Advisory Committee can help increase the detail and usefulness of the metadata section in preparation for the next release cycle.

**Comment by ErinBecker** [comment]
See also https://github.com/datacarpentry/spreadsheets-socialsci/issues/67
