### ISSUE TITLE
Cell references off after inserting column

### ISSUE THREAD

**Issue by karenword** [datacarpentry/spreadsheets-socialsci#5]
References in this instruction: "Select the cell b4 and insert the formula '=IF($F4="Year",$G4,$B3)" need to be adjusted to reflect the column added in a previous step. Should reference G4... H4.

**Comment by karenword** [comment]
(Also holds for similar instructions in Step 4.)
https://data-lessons.github.io/spreadsheets-socialsci/02-Re-formatting%20a%20spreadsheet%20report/

**Comment by karenword** [comment]
Probably related, so I'll add here: there is also a missing instruction for filling in a 4th column starting at d4. This results in there being no "Column4" as referenced in Step 8.

**Comment by PeterSmyth12** [comment]
This was corrected (back in December) by removing a blank column in the spreadsheet, so all of th formula now align correctly. The correct version of the spreadsheet is in the /data folder

**Comment by ErinBecker** [comment]
Thanks for clarifying @karenword. I'll close this issue.
