### ISSUE TITLE
A glossary is needed

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/spreadsheets-socialsci#56]
There is no glossary in http://www.datacarpentry.org/socialsci-workshop/reference/

**Comment by chris-prener** [comment]
Thanks @fmichonneau - if folks have taught this before and want to suggest relevant items - it would be much appreciated!

**Comment by marksnyders** [comment]
Started creating a reference from the ecology lesson #69

**Comment by chris-prener** [comment]
@ErinBecker - if glossary items come up during the onboarding can you add terms to this and I'll get them into the glossary?

**Comment by wesapone** [comment]
I would like to contribute to a glossary project for this lesson to include terms such as matrix, data frames, datasets, and others ...

**Comment by chris-prener** [comment]
would love to have you contribute, @wesapone! feel free to fork the repo and create some initial glossary items.

**Comment by ErinBecker** [comment]
Thanks @wesapone and @marksnyders. @chris-prener - I didn't have any vocab items to add from the onboardings, sorry.

**Comment by chris-prener** [comment]
No worries @ErinBecker!

**Comment by annajiat** [comment]
From https://datacarpentry.org
https://datacarpentry.org/openrefine-socialsci/reference.html
leads 404
but the following is present
https://github.com/datacarpentry/spreadsheets-socialsci/blob/gh-pages/reference.md

How do we correct this?

**Comment by annajiat** [comment]
From https://datacarpentry.org
https://datacarpentry.org/spreadsheets-socialsci/reference.html
leads to 404
but the following is present
https://github.com/datacarpentry/spreadsheets-socialsci/blob/gh-pages/reference.md

How do we correct this?

**Comment by chris-prener** [comment]
The correct url is - https://datacarpentry.org/spreadsheets-socialsci/reference/ @annajiat

**Comment by annajiat** [comment]
Thanks @chris-prener 
Could you please help with correcting URL mentioned at https://datacarpentry.org/lessons/#social-science-curriculum

**Comment by chris-prener** [comment]
This is a concern that has to be addressed a bit higher up the Carpentries org structure than me, I'm afraid, @annajiat. I know this has been forwarded already by @brownsarahm (see https://github.com/datacarpentry/openrefine-socialsci/issues/75#issuecomment-700873844).

**Comment by fmichonneau** [comment]
I think this can now be closed, please re-open if any issue remains.
