### ISSUE TITLE
Dates and Date Formatting needs a file download step/link

### ISSUE THREAD

**Issue by karenword** [datacarpentry/spreadsheets-socialsci#6]
The file for this activity appears to be present in the repo but is not linked anywhere in the episode:
https://github.com/data-lessons/spreadsheets-socialsci/blob/gh-pages/data/dates_1.csv

**Comment by chris-prener** [comment]
thanks @karenword - I'm just getting up to speed with this lesson - you're saying this is an extra file that is not used, correct?

**Comment by karenword** [comment]
This problem appears to have been resolved (or else I failed to note the link previously). There is now a link to this file in the relevant lesson.
