### ISSUE TITLE
libreoffice automatically uses semicolons as separators

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheets-socialsci#62]
Learners who are using LibreOffice for the workshop will have problems with the dataset as the default for LibreOffice is to treat tabs, commas, AND semicolons as delimiters. Need to add this to the instructor notes or a callout. Learners can select to use just commas as delimiters.

**Comment by chris-prener** [comment]
I'll have to download LibreOffice and try and replicate this, but my initial thought is that both the instructor notes and a callout are warranted here...

**Comment by ErinBecker** [comment]
I agree - both Instructor notes and a callout would be good. This happened to two people at the first workshop I was at, and another two people at the second workshop. The fix is quite simple (when opening LibreOffice, deselect the "semicolons" and "tabs" checkboxes, but it isn't something that people will realize they need to do if not prompted.

**Comment by chris-prener** [comment]
*Update*: addressed; will be included in next PR and I'll close after the PR is accepted. There is a note in the `Formatting Data` section of the instructor guide **and** I've added a callout in Episode 01 right before they first import data to start working with it.
