### ISSUE TITLE
Numbers does not have data validation

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheets-socialsci#63]
Learners working on Numbers will need to install LibreOffice. This should be added to Instructor Notes.

**Comment by chris-prener** [comment]
Got it. Happy to add that, but can I ask why? Just curious as a Mac user who does a lot of work in Numbers!

**Comment by ErinBecker** [comment]
Wow, speedy response! I'm at a workshop now and there were several learners using Numbers that didn't have the data validation option so couldn't do that exercise.

**Comment by chris-prener** [comment]
happened to be sitting here doing some Git stuff anyway! 

OK - let me do a little digging on this...

**Comment by enfascination** [comment]
... and Google Sheets does. It's a right click.

**Comment by chris-prener** [comment]
thanks @enfascination - @ErinBecker - should the CAC talk about whether Google Sheets is a good possible option?

**Comment by ErinBecker** [comment]
@enfascination @chris-prener, my advice (based only on seeing this workshop twice) would be to recommend that everyone either use Excel or LibreOffice for the exercises. Most people already have and work with Excel, but for those who don't, LibreOffice installs and is ready to use in about a minute, and doesn't need a specific account (I guess some people may still not have Google accounts).

**Comment by ErinBecker** [comment]
So my concrete suggestion for this is to remove the one reference to Numbers in one of the callout boxes in this lesson, and add a note that everyone should be using either Excel or LibreOffice for this lesson.

**Comment by chris-prener** [comment]
*Update*: addressed; will be included in next PR and I'll close after the PR is accepted
