### ISSUE TITLE
Dates spreadsheet value errors

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheets-socialsci#64]
In the dates as data episode, the spreadsheet has two tabs. The first tab is data stored as DD-MM-YYYY, the second is MM-DD-YYYY. If learners use the wrong tab for their location, they will get a `#VALUE` error. This should be added to Instructor notes.

**Comment by ErinBecker** [comment]
@chris-prener - I'm going to be running onboarding sessions for Instructors to prep for teaching Social Science pilot workshops starting next Monday. Any chance we could get this tip into the Instructor Notes before then? Let me know if you need a hand.

**Comment by chris-prener** [comment]
*Update*: addressed; will be included in next PR and I'll close after the PR is accepted
