### ISSUE TITLE
non-english versions of Excel

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheets-socialsci#65]
If learners are using a non-English language version of Excel, the `=MONTH()`, `=DAY()`, etc functions won't work for them. They will need to type in their language's equivalent of that word in the formula. 

Add to instructor notes?

**Comment by fmichonneau** [comment]
Wow! Does it mean you can't share a spreadsheet file among colleagues that have non-English Excel versions?

**Comment by ErinBecker** [comment]
I'm not sure if Excel will automatically translate function names if you open the sheet in a different version. Either way, I think this is another good illustration of why to share your data files as .csv or something similar (rather than Excel or another proprietary format).

**Comment by ErinBecker** [comment]
@chris-prener - I'm going to be running onboarding sessions for Instructors to prep for teaching Social Science pilot workshops starting next Monday. Any chance we could get this tip into the Instructor Notes before then? Let me know if you need a hand.

**Comment by chris-prener** [comment]
Create a milestone and will go through what I can Thursday morning - sorry these issues fell off my radar!

**Comment by chris-prener** [comment]
*Update:* addressed; will be included in next PR and I'll close after the PR is accepted
