### ISSUE TITLE
Codebooks as social science metadata

### ISSUE THREAD

**Issue by enfascination** [datacarpentry/spreadsheets-socialsci#66]
Just to help bridge the curriculum to social sciences, its worth mentioning familiar forms of metadata in the social sciences. Survey researchers often write codebooks that explain their questions.  Still, a codebook does not have other essential metadata info, like when/where a dataset was collected from.

**Comment by chris-prener** [comment]
thanks for the suggestion @enfascination - what are your thoughts @ErinBecker ?

**Comment by ErinBecker** [comment]
This sounds like a good suggestion and is in line with the [Curriculum Advisors](https://github.com/datacarpentry/spreadsheets-socialsci/issues/67) suggested action items for this lesson before it's next publication in December.
