### ISSUE TITLE
Updating learning outcomes

### ISSUE THREAD

**Issue by chris-prener** [datacarpentry/spreadsheets-socialsci#73]
@sheraaron suggests the following change:

> On this page: https://datacarpentry.org/spreadsheets-socialsci/, I would like to add: (Under - "In this lesson, you will learn:" To enable us to use data successfully)

@ErinBecker and/or @fmichonneau - do changes to the outcomes need to be routed through the CAC?

---

This was originally submitted as issue #71

**Comment by ErinBecker** [comment]
@chris-prener - changes to learning objectives / outcomes do not need to be approved by the CAC, but can be determined by the individual Maintainers for the lesson. I'm not sure exactly what is being proposed here though. Is the outcome that is being added "to enable us to use data successfully"? That seems rather vague to me.

**Comment by chris-prener** [comment]
yeah it seems more motivational than anything else - @sheraaron - can you weigh in and perhaps clarify what you were hoping to do with this outcome?

**Comment by WillavanDijk** [comment]
In the introduction section of this lesson, the learning objective is listed as: Understand how to organize data so computers can make the best use of the data.

I think the verb 'understand' is not measurable. This part of the lesson talks about the differences between the use of spreadsheets from a human and computer perspective. Would it make more sense to state the overall learning objective as:

To describe the importance of data organization to facilitate its use for data analysis programs. 

(or something along these lines?).

**Comment by chris-prener** [comment]
Thanks for the feedback @WillavanDijk - I agree about the word 'understand' - will take a look at this...
