### ISSUE TITLE
Numbers spreadsheet program

### ISSUE THREAD

**Issue by MaraSedlins** [datacarpentry/spreadsheets-socialsci#78]
The Introduction section refers to the Numbers spreadsheet program as an example of what students could use during the workshop (under "Things You'll Need To Complete This Tutorial"), but in the Setup instructions, learners are told not to use Apple's Numbers because it does not contain some of the necessary features.

**Comment by chris-prener** [comment]
Thanks @MaraSedlins - we should remove this reference!

**Comment by josenino95** [comment]
Closing #78 as this was addressed by @zkamvar 's commit on May 3, 2023. Thanks!

**Comment by zkamvar** [comment]
To clear the record: I merely pushed the commit during the lesson transition to The Workbench last year. 

The author who successfully addressed this issue five years ago was @sm4bes 🎉

**Comment by josenino95** [comment]
I didn't realize that when looking at the issue history. In that case, thank you @sm4bes !
