### ISSUE TITLE
Error alert vs. input message

### ISSUE THREAD

**Issue by MaraSedlins** [datacarpentry/spreadsheets-socialsci#82]
In the Quality assurance episode, the example input message given ("Invalid number: Number of household members must be a whole number between 1 and 30.") would be more appropriate as an error alert message.

**Comment by chris-prener** [comment]
I don't use this particular feature - can you give me some feedback in terms of when I would use the input message vs when to use an error message @MaraSedlins ?

**Comment by MaraSedlins** [comment]
The input message is what appears when an input cell is selected, and is meant to give guidance on what values are appropriate. An error message is what appears in a pop-up window when an invalid value is entered. I think a better example of an input message in this case would be "Title: Household members, Input message: Please enter a whole number between 1 and 30."

**Comment by chris-prener** [comment]
Gotcha - thanks @MaraSedlins. I like the example a lot - I'm happy to take a PR or do it myself - up to you!

**Comment by MaraSedlins** [comment]
@chris-prener Great! I'd make a PR except I'm working on a PC instead of a Mac, so the screenshot would be inconsistent with the rest of the images. Could you make the change, please?

**Comment by chris-prener** [comment]
No worries @MaraSedlins - we can take care of that! Thanks for all your contributions to this repo!
