### ISSUE TITLE
01-format-data/index.html, one link is 404

### ISSUE THREAD

**Issue by Carreau** [datacarpentry/spreadsheets-socialsci#88]
> ... Looking at an entry for a particular variable, such as **the variable SEX**, provides valuable information...

Link lead to a 404.

**Comment by chris-prener** [comment]
Thanks @Carreau - we'll try and track down a new link for this...

**Comment by bencomp** [comment]
It looks like the link works.

**Comment by Carreau** [comment]
Yep, seems like it works. Closing.
