### ISSUE TITLE
readme file and SAFI_clean.csv

### ISSUE THREAD

**Issue by AliNite** [datacarpentry/spreadsheets-socialsci#94]
Hi I'm planning to teach this fantastic workshop in a couple of weeks at the University of Bath. As I've been going through the lessons a couple of things struck me. The first was the need for a readme file for the data files so that we can model good research data management practice to students (I'm a research data librarian). The second is that SAFI_clean.csv has a couple of variables (items_owned and months_lack_food) that would be problematic to analyse in most statistical analysis programmes because they have multiple values that are all in a different order. My concern is that by calling this file 'clean' we are then saying that it is ready to go.  I have attached a readme file for the data files that you are very welcome to use (you will need to remove references to the University of Bath). I have also attached a version of SAFI_clean where there is a worksheet where all text variables have been coded to numerical variables and items_owned and months_lack_food have also been coded into yes / no variables using and IF statement that will search for text variables. There is also a worksheet in the workbook with documentation to accompany the changes I've made to SAFI_clean. This could be provided as a resource for tutors if you think it would be useful. 

All the best
Alison Nightingale (University of Bath, UK)
[SAFI_clean_processed.xlsx](https://github.com/datacarpentry/spreadsheets-socialsci/files/3686683/SAFI_clean_processed.xlsx)
[SAFI_readme.txt](https://github.com/datacarpentry/spreadsheets-socialsci/files/3686684/SAFI_readme.txt)

**Comment by chris-prener** [comment]
Hi @AliNite - thanks for opening this. Do you want to create a pull request for the readme? 

For the spreadsheet, I want to look through how its used and think about whether there would be any side effects here with this change.

**Comment by AliNite** [comment]
HI Chris I'm completely new to GitHub, how to I create a pull request? 

Re the spreadsheet - no worries at all. Looking at the course it seems it it usually followed immediately by the OpenRefine course which then deals with (to some extent) the two variables that I mentioned. So for people who are following it with OpenRefine then you wouldn't want to use the updated version of the spreadsheet. It is entirely up to you - as I had done the work I thought I would put it out there for sharing to save anyone else the effort :o)

**Comment by chris-prener** [comment]
hi @AliNite - you'd need to create a [fork](https://help.github.com/en/articles/fork-a-repo) of this repo, edit the README itself. Once you've edited the README, you can then push your changes to GitHub and [create a pull request](https://help.github.com/en/articles/about-pull-requests). If this seems like too much, I can also make the changes - but its a great way to get some experience using Git/GitHub.

re the spreadsheet, the solution may be to have both with that note in the instructor resources that if it comes right after OpenRefine, this may not be an issues.

**Comment by AliNite** [comment]
Thanks @chris-prener I'll have a go on Monday when my colleague is in (he is very familiar with it!) just in case I get stuck and mess something up! Its good to learn!

**Comment by chris-prener** [comment]
sounds good!

**Comment by AliNite** [comment]
@chris-prener I have (I think) edited the README file and have created a pull request for the changes. Please do let me know if I haven't done this properly or if you would like me to make any other changes.

**Comment by chris-prener** [comment]
Great - I'll take a look tomorrow! Thanks @AliNite

**Comment by chris-prener** [comment]
#96 merged, so this can be closed!
