### ISSUE TITLE
num_membrs used to describe no_membrs column

### ISSUE THREAD

**Issue by colinquirk** [datacarpentry/spreadsheets-socialsci#98]
In 04-quality-assurance, num_membrs seems to be incorrectly used to describe the no_membrs column. I noticed this in the Restricting data to a numeric range section and in the final tip. The data seems to have no_membrs, so I'm assuming that is the correct name.

**Comment by chris-prener** [comment]
Thanks @colinquirk - I'll fix this! Appreciate your patience...

**Comment by josenino95** [comment]
This seems to be already fixed in the lesson, as I checked and the Quality Assurance episode already has the correct references to the "no_membrs" column.
