### ISSUE TITLE
Typo in exercise: it's should be its 

### ISSUE THREAD

**Issue by angela-li** [datacarpentry/spreadsheets-socialsci#99]
In the Dates as data exercise here: http://datacarpentry.org/spreadsheets-socialsci/03-dates-as-data/#regional-date-formatting

**Comment by chris-prener** [comment]
Thanks @angela-li - I'll fix this! Appreciate your patience...

**Comment by chris-prener** [comment]
Fixed by #100 - thanks @burrowsdt and @angela-li !
